name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci  # Adaptez pour React/Vue/etc.

      - name: Build
        run: npm run build

      - name: Deploy to S3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3  # Changez selon votre région
      - run: aws s3 sync build/ s3://votre-bucket --delete